//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnos_dual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumnos_dual()
        {
            this.AlumnoXProyecto = new HashSet<AlumnoXProyecto>();
        }
    
        public int IdAlumno { get; set; }
        public int Matricula { get; set; }
        public string Nombre_Alumno { get; set; }
        public string Apellido_Alumno { get; set; }
        public System.DateTime Fecha_Nacimiento_Alumno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoXProyecto> AlumnoXProyecto { get; set; }
    }
}
