//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesores_dual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asesores_dual()
        {
            this.AsesorXProyecto = new HashSet<AsesorXProyecto>();
        }
    
        public int IdAsesor { get; set; }
        public int NSS { get; set; }
        public string Nombre_Asesor { get; set; }
        public string Apellido_Asesor { get; set; }
        public System.DateTime Fecha_Nacimiento_Asesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsesorXProyecto> AsesorXProyecto { get; set; }
    }
}
