//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsesorXProyecto
    {
        public int Id { get; set; }
        public int Id_Asesor { get; set; }
        public int Id_Proyecto { get; set; }
    
        public virtual Asesores_dual Asesores_dual { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
